apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: site-strootje
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
    - host: strootje.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: site-strootje
                port: { name: http }
            pathType: Prefix
  tls:
    - hosts: [strootje.com]
      secretName: site-strootje-cert
