apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: strootje-public

commonLabels:
  app.kubernetes.io/name: site-strootje

images:
  - { name: ghcr.io/strootje/site-strootje, newTag: main }

resources:
  - deployment.yml
  - ingress.yml
  - service.yml
