apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websites-public

commonLabels:
  app.kubernetes.io/name: website-strootje

commonAnnotations:
  app.kubernetes.io/version: 1.0.0

resources:
  - deployment.yml
  - ingress.yml
  - service-account.yml
  - service.yml
