name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: strootje/strooweb-workflows/workflows/build-and-deploy.yml@main
    with:
      IMAGE_NAME: strootje/site-strootje
      KUBE_NAMESPACE: strootje-public
    secrets: inherit